name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2]
    steps:
    - uses: actions/checkout@v3
    - name: Run Parallel Job
      run: |
        #python main.py ${{ matrix.number }}
        echo test
    - name: Generate Output
      id: generate_output
      run: |
        echo asd ${{ matrix.number }} > ${{ matrix.number }}
        ID=$(cat ${{ matrix.number }})
        echo "testmo-run-id=$ID" >> $GITHUB_OUTPUT
    - run: |
        echo "${{ steps.matrix.outputs.generate_output }}"

  parallel:
    needs: parallel-jobs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Retrieve Output
      run: |
        echo "${{ needs.parallel-jobs.outputs['generate_output'][matrix.number].testmo-run-id }}"
        git config user.name github-actions
        git config user.email github-actions@github.com
        #git add output_${{ matrix.number }}.dat
        #git add .
        #git commit -m "generated"
        #git push
