name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [64, 66, 67, 68, 70, 71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8' 
    - run: |
        #apt update
        sudo apt install ffmpeg -y
    - name: Create and Save ID File
      run: |
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.txt
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.mp3
        #python main.py ${{ matrix.number }}
        echo test12 > output_${{ matrix.number }}.dat
    - name: Push to GitHub (Attempt 1)
      id: push_attempt_1
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push -f
        sleep 2
    - name: Push to GitHub (Attempt 2)
      id: push_attempt_2
      if: failure()
      run: |
        cd data
        git push -f
        sleep 4
    - name: Push to GitHub (Attempt 3)
      id: push_attempt_3
      if: failure() && steps.push_attempt_2.outcome != 'success'
      run: |
        cd data
        git push -f
        sleep 3
    - name: Push to GitHub (Attempt 4)
      id: push_attempt_4
      if: failure() && steps.push_attempt_3.outcome != 'success'
      run: |
        cd data
        git push -f
        sleep 4
    - name: Push to GitHub (Attempt 5)
      id: push_attempt_5
      if: failure() && steps.push_attempt_4.outcome != 'success'
      run: |
        cd data
        git push -f
        sleep 5
