name: Parallel Jobs Example

on:
  push:
    branches:
      - "test_edge"
jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 4
      matrix:
        number: [3]
    steps:
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8' 
    - run: |
        pip install -q edge-tts
    - name: Create and Save ID File
      run: |
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.txt
        wget https://raw.githubusercontent.com/mooghen2s/data_top/test_edge/main.py
        #python main.py ${{ matrix.number }}
        date +%s > output_${{ matrix.number }}.mp3
        
    - name: Push to GitHub (Attempt 1)
      id: push_attempt_1
      if: always()
      run: |
        git init
        #git clone --single-branch --branch top_mp3 https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        #cp output_${{ matrix.number }}.mp3 data/output_${{ matrix.number }}.mp3
        NUMBERS=$(date +%s)
        date +%s > output_${{ matrix.number }}.mp3
        #cd data
        date +%s > README.md
        echo output_${{ matrix.number }} >> README.md
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git branch -m top_mp3
        git add output_${{ matrix.number }}.mp3
        sleep 4
        git commit -m "test ${{ matrix.number }} time $NUMBERS"
        git push --no-verify https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git top_mp3
    - name: Push to GitHub (Attempt 2)
      id: push_attempt_2
      if: ${{ failure() && steps.push_attempt_1.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        #cd data
        date +%s >> README.md
        sleep 4
        git push -u --no-verify https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git top_mp3
    - name: Push to GitHub (Attempt 3)
      id: push_attempt_3
      if: ${{ failure() && steps.push_attempt_2.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        #cd data
        sleep 6
        date +%s >> README.md
        git push -u --no-verify https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git top_mp3
    - name: Push to GitHub (Attempt 4)
      id: push_attempt_4
      if: ${{ failure() && steps.push_attempt_3.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        #cd data
        sleep 8
        date +%s >> README.md
        git push -u --no-verify https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git top_mp3
    - name: Push to GitHub (Attempt 5)
      id: push_attempt_5
      if: ${{ failure() && steps.push_attempt_4.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        #cd data
        sleep 10
        date +%s >> README.md
        git push -u --no-verify https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git top_mp3
