name: Parallel Jobs Example

on:
  push:
    branches:
      - "test_edge"
jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        number: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]
    steps:
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8' 
    - run: |
        pip install -q edge-tts
    - name: Create and Save ID File
      run: |
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.txt
        wget https://raw.githubusercontent.com/mooghen2s/data_top/test_edge/main.py
        python main.py ${{ matrix.number }}
        #date +%s > output_${{ matrix.number }}.mp3
        
    - name: Push to GitHub (Attempt 1)
      id: push_attempt_1
      if: always()
      run: |
        #git init
        git clone --no-checkout --single-branch --branch top_mp3 https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.mp3 data/output_${{ matrix.number }}.mp3
        NUMBERS=$(date +%s)
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.mp3
        sleep 4
        git commit -m "test ${{ matrix.number }} time $NUMBERS"
        for i in {1..15}; do
          git push && break
          echo "Retrying in 10s..."
          sleep 5
        done
    - name: Push to GitHub (Attempt 2)
      id: push_attempt_2
      if: ${{ failure() && steps.push_attempt_1.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        cd data
        date +%s >> README.md
        sleep 4
        git push
    - name: Push to GitHub (Attempt 3)
      id: push_attempt_3
      if: ${{ failure() && steps.push_attempt_2.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        #cd data
        sleep 6
        date +%s >> README.md
        git push 
    - name: Push to GitHub (Attempt 4)
      id: push_attempt_4
      if: ${{ failure() && steps.push_attempt_3.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        #cd data
        sleep 8
        date +%s >> README.md
        git push
    - name: Push to GitHub (Attempt 5)
      id: push_attempt_5
      if: ${{ failure() && steps.push_attempt_4.conclusion == 'failure' }}
      env:
          matrix_number: ${{ matrix.number }}
      run: |
        #cd data
        sleep 10
        date +%s >> README.md
        git push
