name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2]
    steps:
    - uses: actions/checkout@v4
    - name: Run Parallel Job
      run: echo "test"
    - name: Create and Save ID File
      run: echo "asd ${{ matrix.number }}" > output_${{ matrix.number }}.dat
    - name: Read ID File and Set Output
      run: |
        ls
    - name: push to github
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push
