name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2]
    steps:
    - uses: actions/checkout@v3
    - name: Run Parallel Job
      run: |
        #python main.py ${{ matrix.number }}
        echo test
    - name: Run Parallel Job
      run: |
        echo asd ${{ matrix.number }} > ${{ matrix.number }}
        ID${{ matrix.number }}=cat ${{ matrix.number }}
        echo "testmo-run-id=$ID" >> $GITHUB_OUTPUT
  parallel:
    needs: parallel-jobs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Parallel Job
      run: |
        echo "${{ needs.parallel-jobs.outputs.testmo-run-id${{ matrix.number }} }}"
        git config user.name github-actions
        git config user.email github-actions@github.com
        #git add output_${{ matrix.number }}.dat
        #git add .
        #git commit -m "generated"
        #git push
