name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]
        
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8' 
    - run: |
        #apt update
        sudo apt install ffmpeg -y
    - name: Create and Save ID File
      run: |
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.txt
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.mp3
        python main.py ${{ matrix.number }}
    - name: Push to GitHub (Attempt 1)
      id: push_attempt_1
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push -f
    - name: Push to GitHub (Attempt 2)
      id: push_attempt_2
      if: failure()
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push -f
    - name: Push to GitHub (Attempt 3)
      id: push_attempt_3
      if: failure()
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push -f
    - name: Push to GitHub (Attempt 4)
      id: push_attempt_4
      if: failure()
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push -f
    - name: Push to GitHub (Attempt 5)
      id: push_attempt_5
      if: failure()
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push -f
    - run: echo done
