name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2]
    
    steps:
    - uses: actions/checkout@v3
    - name: Run Parallel Job
      run: echo "test"
    - name: Create and Save ID File
      id: create-file
      run: echo "asd ${{ matrix.number }}" > ${{ matrix.number }}
    - name: Read ID File and Set Output
      id: set-output
      run: |
        ID=$(cat ${{ matrix.number }})
        echo "testmo-run-id=$ID" >> $GITHUB_OUTPUT
    outputs:
      testmo-run-id-${{ matrix.number }}: ${{ steps.set-output.outputs.testmo-run-id }}
  parallel:
    needs: parallel-jobs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print Outputs
      run: |
        for number in 1 2; do
          ID=$(echo "${{ needs.parallel-jobs.outputs.testmo-run-id-$number }}")
          echo "ID for job $number: $ID"
        done
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Commit and Push Changes
      run: |
        # Uncomment and adjust the following lines as needed
        # git add output_${{ matrix.number }}.dat
        # git add .
        # git commit -m "generated"
        # git push
