name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1, 2]
    outputs:
      testmo-run-id-${{ matrix.number }}: ${{ steps.set-output.outputs.testmo-run-id }}
    steps:
    - uses: actions/checkout@v3
    - name: Run Parallel Job
      run: echo "test"
    - name: Create and Save ID File
      id: create-file
      run: echo "asd ${{ matrix.number }}" > output_${{ matrix.number }}.dat
    - name: Read ID File and Set Output
      id: set-output
      run: |
        ID=$(cat output_${{ matrix.number }}.dat)
        echo "testmo-run-id=$ID" >> $GITHUB_ENV
    
  parallel:
    needs: parallel-jobs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print Outputs
      run: |
        for number in 1 2; do
          ID=$(echo "${{ needs.parallel-jobs.outputs['testmo-run-id-' . $number ] }}")
          echo "ID for job $number: $ID"
        done
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add output_*.dat
        git commit -m "Generated IDs"
        git push
