name: Parallel Jobs Example

on: [push]

jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [43, 44]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8' 
    - run: |
        #apt update
        sudo apt install ffmpeg -y
    - name: Run Parallel Job
      run: wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.txt
    - name: download mp3
      run: wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.mp3
    - name: Create and Save ID File
      run: |
        ls
        python main.py ${{ matrix.number }}
        #echo "asd ${{ matrix.number }}" > output_${{ matrix.number }}.dat
    - name: Read ID File and Set Output
      run: |
        ls
    - name: push to github
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        cd data
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add output_${{ matrix.number }}.dat
        git commit -am "test ${{ matrix.number }}"
        git push
