name: Parallel Jobs Example

on: [push]
jobs:
  parallel-jobs:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 8
      matrix:
        number: [64, 74, 82]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.0
      with:
        python-version: '3.8' 
    - run: |
        sudo apt install ffmpeg -y
    - name: Create and Save ID File
      run: |
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.txt
        wget https://raw.githubusercontent.com/mooghen2s/data/top_tier_edge/top_tier_edge/output_${{ matrix.number }}.mp3
        python main.py ${{ matrix.number }}
        #date +%s > output_${{ matrix.number }}.dat
        
    - name: Push to GitHub (Attempt 1)
      id: push_attempt_1
      if: always()
      run: |
        git clone --single-branch --branch test https://mooghen2s:${{ secrets.TOKEN }}@github.com/mooghen2s/data.git
        cp output_${{ matrix.number }}.dat data/output_${{ matrix.number }}.dat
        
        cd data
        date +%s > README.md
        echo output_${{ matrix.number }} >> README.md
        git config --global user.name "mooghen2s"
        git config --global user.email "juaimahen.a52@gmail.com"
        git add 'output_${{ matrix.number }}.dat' 'README.md'
        git commit -m "test ${{ matrix.number }}"
        git push -f 
        sleep 2
    - name: Push to GitHub (Attempt 2)
      id: push_attempt_2
      if: ${{ failure() && steps.push_attempt_1.conclusion == 'failure' }}
      run: |
        cd data
        date +%s >> README.md
        sleep 4
        git push -f
    - name: Push to GitHub (Attempt 3)
      id: push_attempt_3
      if: ${{ failure() && steps.push_attempt_2.conclusion == 'failure' }}
      run: |
        cd data
        sleep 6
        date +%s >> README.md
        git push -f
    - name: Push to GitHub (Attempt 4)
      id: push_attempt_4
      if: ${{ failure() && steps.push_attempt_3.conclusion == 'failure' }}
      run: |
        cd data
        sleep 8
        date +%s >> README.md
        git push -f
    - name: Push to GitHub (Attempt 5)
      id: push_attempt_5
      if: ${{ failure() && steps.push_attempt_4.conclusion == 'failure' }}
      run: |
        cd data
        sleep 10
        date +%s >> README.md
        git push -f
